#!/usr/bin/env python


import numpy as np
from CPM import CPM
from matplotlib import pyplot as plt
from skimage import measure
import os
L=40
#q=3

size=L**2
V0=10

cells=[50,50]

P=CPM(L,cells=cells,V0=V0)

P.J=np.array([[0,1,1],[1,5,100],[1,100,5]])
T=100000
for t in range(T):
		P.ModifiedMetropolisStep()
		
print(P.J)

plt.figure()
plt.imshow(P.s)

T=np.zeros((L,L),int)
for i in range(L):
	for j in range(L):
		T[i,j]=P.type[P.s[i,j]]
plt.figure()
plt.imshow(T)
plt.show()
